name: Auto Build
on:
  push:
    branches:
      - "master"
jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out the repo
        uses: actions/checkout@v3
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_PASSWORD  }}
      - name: Build docker image
        run: |
          docker build --platform linux --tag keshus/examenweb:latest -f Dockerfile .
      - name: Publish website image
        run: |
          docker push keshus/examenweb:latest